version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwsss*1348394#
      POSTGRES_DB: testsuite
    ports:
      - "127.0.0.1:5432:5432"

  mariadb:
    restart: always
    image: mariadb:11
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: passwsss*1348394#
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testsuite
    ports:
      - "127.0.0.1:3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      MSSQL_SA_PASSWORD: Mssql123mssql-
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "127.0.0.1:1433:1433"
