version: "3.8"
services:
  db:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password*1123456879#"
      POSTGRES_DB: "testsuite"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "testsuite"
      MYSQL_ROOT_PASSWORD: "password*1123456879#"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      MSSQL_SA_PASSWORD: "Mssql123mssql-"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    expose:
      - "1433"
    ports:
      - "1433:1433"
