site_name: Databasez
site_description: Async database support for Python.
site_url: https://databasez.dymmond.com
docs_dir: docs/generated
site_dir: site

theme:
    name: "material"
    custom_dir: docs/overrides
    language: en
    palette:
        - scheme: "default"
          primary: "cyan"
          accent: "amber"
          media: "(prefers-color-scheme: light)"
          toggle:
              icon: "material/lightbulb"
              name: "Switch to dark mode"
        - scheme: "slate"
          media: "(prefers-color-scheme: dark)"
          primary: "cyan"
          accent: "amber"
          toggle:
              icon: "material/lightbulb-outline"
              name: "Switch to light mode"
    favicon: statics/images/favicon.ico
    logo: statics/images/logo-white.png
    features:
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.copy
        - navigation.indexes
        - navigation.path

repo_name: dymmond/databasez
repo_url: https://github.com/dymmond/databasez
edit_uri: ""
plugins:
    - search

nav:
    - Databasez: "index.md"
    - Architecture Overview: "architecture-overview.md"
    - Core Concepts: "core-concepts.md"
    - Database: "database.md"
    - Database URL: "database-url.md"
    - Queries: "queries.md"
    - Connections & Transactions: "connections-and-transactions.md"
    - Integrations: "integrations.md"
    - Extra drivers and overwrites: "extra-drivers-and-overwrites.md"
    - Test Client: "test-client.md"
    - Tests & Migrations: "tests-and-migrations.md"
    - Troubleshooting: "troubleshooting.md"
    - Vendors: "vendors.md"
    - Databasez People: "databasez-people.md"
    - Contributing: "contributing.md"
    - Sponsorship: "sponsorship.md"
    - Release Notes: "release-notes.md"

markdown_extensions:
    - attr_list
    - toc:
          permalink: true
    - admonition
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format ""
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - md_in_html

extra:
    alternate:
        - link: /
          name: English
          lang: en

extra_css:
  - stylesheets/extra.css
