#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'databasez.egg-info' ] ; then
    rm -r databasez.egg-info
fi
if [ -d '.mypy_cache' ] ; then
    rm -r .mypy_cache
fi
if [ -d '.pytest_cache' ] ; then
    rm -r .pytest_cache
fi
if [ -d '.ruff_cache' ] ; then
    rm -r .ruff_cache
fi

find databasez -type f -name "*.py[co]" -delete
find databasez -type d -name __pycache__ -delete
